id: P008140
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 13:04:08.125834
source_metadata:
  id: bdr:W1KG24021
  title: ཐང་རྒྱལ་རབས་ཀྱི་སྙན་ཚིག་ཁག་སུམ་བརྒྱ།
  author: ''
  volumes:
    907ce029c1cc4a0ca7b96b601001005e:
      image_group_id: I1KG24098
      title: Volume 1 of thang rgyal rabs kyi snyan tshig khag sum brgya/
      volume_number: 1
      total_pages: 346
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
