id: P008140
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24021
  title: ཐང་རྒྱལ་རབས་ཀྱི་སྙན་ཚིག་ཁག་སུམ་བརྒྱ།
  author: ''
  volumes:
    3fb71111a5dd4e0ba10fc6b86b645434:
      image_group_id: I1KG24098
      title: ''
      volume_number: 1
      total_pages: 346
ebook_metadata:
  title: ཐང་རྒྱལ་རབས་ཀྱི་སྙན་ཚིག་ཁག་སུམ་བརྒྱ།
  author: ''
  sku: P008140
  cover: cover.jpg
  layers:
  - pagination
